---
title: "dataflow/ERR/2023_006"
linkTitle: "ERR/2023_006"
weight: 1
type: docs
description: >
  Dataflow job failure when the subnetwork does not have Private Google Access enabled
---

**Product**: [Dataflow](https://cloud.google.com/dataflow)\
**Rule class**: ERR - Something that is very likely to be wrong

### Description

Dataflow job fails if Private Google Access is disabled on the Subnetwork used by the job, which is required when Dataflow workers only use Private addresses. Private Google Access allows workers to connect to external Google Api's and Services.

You can search in the Logs Explorer with the logging query:
```
resource.type="dataflow_step"
severity=ERROR
"does not have Private Google Access, which is required for usage of private IP addresses by the Dataflow workers"
```

### Remediation

Enable Private Google Access on the subnetworks used by the Dataflow jobs.

### Further information

[Private Google Access](https://cloud.google.com/vpc/docs/configure-private-google-access#configuring_access_to_google_services_from_internal_ips)
